# ADEVICE <input_output_device>
# Found using 'aplay -l' and 'arecord -l'
ADEVICE plughw:1,0
#ADEVICE pipewire

# How many audio channels to use
ACHANNELS 1

# Baud rate (default is 1200 baud)
MODEM 1200

# PTT RIG <Hamlib rig number> <device address>
# To find rig number run: 'rigctl -l | grep <radio name/id>'
PTT RIG 3085 /dev/ttyACM0
#PTT RIG 2 127.0.0.1:4532

# Add an optional delay for use with VOX
# TXDELAY 30

# Enables KISS protocol on the specified port
KISSPORT 8001
# Disables the AGW port
AGWPORT 0

# FX.25 transmit: adds FEC to outgoing AX.25 frames
FX25TX 1
